export const paintImage = require('/public/images/home/paint.png')
export const leftImage = require('/public/images/home/leftImage.png')
export const rightImage = require('/public/images/home/rightImage.png')
export const bottomImage = require('/public/images/home/bottomImage.png')
export const bottomCircleImage = require('/public/images/home/bottomCircleImage.png')
